console.log('$-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_');
console.log('$                OrchiDB             ');
console.log('$-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_');
console.log('$ ');
console.log('$ ');
console.log('$Welcome to OrchiDB. A lightweight, document-oriented database managment system for JavaScript.');
console.log('$For more information, read the README.md file in the source code.');
console.log('$To use this database, copy the files in the OrchiDB folder or fork the code to your own project.');
console.log('$ ');
console.log('$ ');
console.log('$-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_');